services:
  nginx:
    image: nginx:1.27.4
    restart: always
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/static
      - ./media:/media
    depends_on:
      - admin_panel

  redis:
    image: redis:7.4.2
    restart: always
    # Delete or comment ports for production (2 lines)
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}
    volumes:
      - redis:/data

  postgres:
    image: postgres:16.8
    env_file: .env
    # Delete or comment ports for production (2 lines)
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 30s
      retries: 5

  admin_panel:
    build:
      context: .
    entrypoint: ["bash", "entrypoint.sh"]
    command: ["gunicorn", "backend.wsgi", "-b", "0.0.0.0:8000"]
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 9000:8000
    volumes:
      - ./static:/static
      - ./media:/media

  bot:
    build:
      context: .
    env_file:
      - .env
    restart: always
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: ['python', 'manage.py', 'runbot']
  worker:
    build:
      context: .
    command: celery -A backend worker --loglevel info
    env_file: .env
    environment:
      REDIS_HOST: redis
      DB_HOST: postgres
    restart: always
    volumes:
      - ./media:/media
    depends_on:
      - postgres
      - admin_panel
      - redis

volumes:
  redis:
  postgres:
